# Site settings
title: NAF Architect
email: info@nafarch.com
description: Showcasing part of our soul to the world through architecture.
baseurl: "/nafarch-full" # the subpath of your site, e.g. /blog
url: "satuhearty.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/nafarch-logo.png
font-awesome-icon-logo:

# Social settings
github_username:
twitter_username:
facebook_URL: nafarch
instagram_username: nafarch
dribbble_username:
500px_username:
phone: +60173232024

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
